apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xgjbdgc4e-nodejs
  janus-idp.io/tekton: xgjbdgc4e-nodejs
  backstage.io/kubernetes-id: xgjbdgc4e-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xgjbdgc4e-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
